name: Release

on:
  push:
    tags:
      - "v*" # v0.1.0 のようなタグが push された時に起動

permissions:
  contents: write # リリースを作成し、ファイルをアップロードするために必要

jobs:
  build-and-release:
    name: Build and Release on Windows
    runs-on: windows-latest # Inno Setup を動かすため Windows を使用

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Build Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/installer/LogBee-setup.exe
            target/release/LogBee.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu:
    name: Build and Release on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build Release
        run: cargo build --release

      - name: Create Deb Package
        run: cargo deb --no-build # すでにビルド済みなので no-build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/debian/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-rpm:
    name: Build and Release on Fedora
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: dnf install -y gcc-c++ openssl-devel rpm-build curl

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build binary
        run: |
          source $HOME/.cargo/env
          cargo build --release

      - name: Create RPM
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          if [ "$VERSION" = "" ]; then VERSION="0.1.0"; fi
          # 1. RPMビルド構造の作成
          mkdir -p ~/rpmbuild/{SOURCES,SPECS,RPMS,BUILD,BUILDROOT}
          # 2. バイナリを BUILD ディレクトリ直下にコピー
          # ※ rpmbuild はデフォルトでここを %{_builddir} として参照します
          cp target/release/logbee ~/rpmbuild/BUILD/
          # 3. ビルド実行
          rpmbuild -bb --define "_version $VERSION" logbee.spec
          # 4. 生成物の回収
          cp ~/rpmbuild/RPMS/x86_64/*.rpm ./

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.rpm"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
